matrix:
  include:
    - language: python
      python: 3.6
      install:
        - pip install -r backend/requirements.txt
      before_script:
        - cd backend/
      script:
        - py.test

    - language: node_js
      node_js: 10.1
      
      before_install:
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start

      before_script:
        - cd frontend/  
        - npm install -g angular-cli
        - npm install -g karma
        - npm install
        - ng build
      
      script: 
        - ng test

notifications:
  email: never

after_success:
  coveralls
